add_whitespace:
  type: bool
  default: false
svg_icons:
  type: "list"
  list_type: "compact"
  default: "fab-discord|fab-github|fas fa-poll-h"
header_links:
  type: objects
  default:
    - title: "OpenBMC Discord channel"
      icon: "fab-discord"
      url: "https://discord.gg/6nJPuuKm2V"
      view: "vdm"
      target: "blank"
    - title: "OpenBMC GitHub repository"
      icon: "fab-github"
      url: "https://github.com/openbmc"
      view: "vdm"
      target: "blank"
    - title: "OpenBMC Gerrit"
      icon: "fas fa-poll-h"
      url: "https://gerrit.openbmc-project.xyz"
      view: "vdm"
      target: "blank"
  schema:
    name: "link"
    properties:
      title:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 1000
      icon:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 2048
      url:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 2048
          url: true
      view:
        type: enum
        choices:
          - vdm
          - vdo
          - vmo
      width:
        type: integer
        required: false
      target:
        type: enum
        choices:
          - blank
          - self
